language: python

# python version
python:
  - "3.6.4"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage

# command to run tests
script:
  - virtualenv env
  - coverage run --source=app -m pytest
  - coverage report
  - coveralls
  
# Post coverage results to coverage.io
after-success:
  - coveralls