language: python

# python version
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - virtualenv env
  - pytest --cov=tests/
  
# Post coverage results
after-success:
  - coveralls